name: .NET Desktop CI


on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: .NET Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Abhängigkeiten wiederherstellen
      run: |
          $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
          dotnet restore $sln.FullName

    - name: Projekt bauen
      run: |
           $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
           dotnet build $sln.FullName --no-restore --configuration Release

    - name: Unit Tests ausführen
      run: |
            $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
            dotnet test $sln.FullName --no-build --verbosity normal
